/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarDesktop: typeof import('./src/components/shell/AppBarDesktop.vue')['default']
    AppBody: typeof import('./src/components/shell/AppBody.vue')['default']
    CityList: typeof import('./src/components/shared/CityList.vue')['default']
    ComponentExplanation: typeof import('./src/components/shared/ComponentExplanation.vue')['default']
    ErrorMessage: typeof import('./src/components/errors/ErrorMessage.vue')['default']
    ForecastHourly: typeof import('./src/components/forecasts/ForecastHourly.vue')['default']
    ForecastOverview: typeof import('./src/components/forecasts/ForecastOverview.vue')['default']
    ForecastStats: typeof import('./src/components/forecasts/ForecastStats.vue')['default']
    ForecastTemperature: typeof import('./src/components/forecasts/ForecastTemperature.vue')['default']
    InfoBlock: typeof import('./src/components/shared/InfoBlock.vue')['default']
    PageTitle: typeof import('./src/components/shared/PageTitle.vue')['default']
    PortalList: typeof import('./src/components/shared/PortalList.vue')['default']
    SearchBox: typeof import('./src/components/shell/SearchBox.vue')['default']
    SimpleDialog: typeof import('./src/components/shared/SimpleDialog.vue')['default']
    TrendDialogSummary: typeof import('./src/components/shared/TrendDialogSummary.vue')['default']
    TrendingValue: typeof import('./src/components/shared/TrendingValue.vue')['default']
  }
}
